### ISSUE TITLE
Set up the SQL Database

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#1]
## Description
We need a database to hold all the inventory items/data.

## Tasks
- [x] Create an inventory database using a SQL database
- [x] Connect to the database via Python Flask
- [x] Set up basic CRUM operations to interact with the database

## Done Done Criteria
1. Test that the SQL database is live, interactable, and editable
