### ISSUE TITLE
Update T-Square Site and Wiki

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#15]
## Description
We need to accomplish some initial Junior Design tasks that our instructors have placed upon us.

## Tasks
- [x] Update Team Charter
- [x] Update Iteration Plan
- [x] Update Meeting Minutes
- [x] Update Site Information
- [x] Link Site Information w/ Github
- [x] Link Site Information w/ Client Charter
- [x] Add Instructors to Site with 'Maintain' Access

## Done Done Criteria
1. Review over all the tasks with the team
2. Double-check that all tasks are completed and visible to the graders/instructors

**Comment by zehro** [comment]
Only have Iteration Plan left.
