### ISSUE TITLE
Set Up Zenhub Workflow

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#16]
## Description
By the recommendation (almost required) of our instructors, we are using Zenhub to keep track of our workflow and issues.

This issue is to set up all the templates and orient all team members with the new workflow.

## Tasks
- [x] Set up Epic Template
- [x] Set up Issue Template
- [x] Set up User Story Template
- [x] Discuss the new workflow and practice project management with team members

## Done Done Criteria
1. Check if the entire project team understands the Zenhub workflow
