### ISSUE TITLE
Prepare DB Futures Information Presentation

### ISSUE THREAD

**Issue by KSholl** [zehro/UAH-Theatre#24]
## Description
After project completion hosting will need to be controlled by the UAH staff. We should research different hosting solutions and present the findings to Amy so that she can make a decision as to what type of DB hosting they want so that we can customize our application to work with that solution.

## Tasks
- [x] Research MySQL Hosting solutions
- [x] Prepare an email to send findings to Amy
- [x] Receive Amy's choice for the eventual DB host

## Done Done Criteria
1. Amy responds to email (will cc everyone)
